# Generated by Django 4.2 on 2024-11-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SquaresDifference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_number', models.PositiveIntegerField()),
                ('value', models.PositiveIntegerField()),
                ('occurrences', models.PositiveIntegerField()),
                ('last_requested', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
