# Generated by Django 4.2 on 2024-11-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squaresdifference',
            name='last_requested',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
