# Generated by Django 4.2 on 2024-11-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_squaresdifference_last_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triplet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.PositiveIntegerField()),
                ('b', models.PositiveIntegerField()),
                ('c', models.PositiveIntegerField()),
                ('product', models.PositiveIntegerField()),
                ('is_triplet', models.BooleanField()),
                ('occurrences', models.PositiveIntegerField(default=0)),
                ('last_requested', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='triplet',
            constraint=models.UniqueConstraint(fields=('a', 'b', 'c'), name='unique_a_b_c'),
        ),
    ]
